greeting:
  message: "hello"
  name: "quarkus"

quarkus:
  datasource:
    db-kind: mysql
    jdbc:
      url: jdbc:mysql://localhost:3306/dmeeting-quarkus
    username: root
    password: root
  hibernate-orm:
    database:
      generation: create